export const ROUTER = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ALLWORK: '/work',
  MY_JOB: '/my-jobs',
  REPORT: '/reports',
  MESSAGE: '/messages',
  NOTIFICATION: '/notification',
  CONTACT: '/contact',
  PROFILE: '/profile',
  SETTING: '/setting',
  CREATE_JOB: '/client/create-job',
  PAYMENTS: '/payments',
  BILL: '/bill-earn',
  CLIENT:'/client',
  FREELANCER:"/freelancer",
  BEST_MATCHES:"/best-matches",
};
