export enum MODAL_TYPE {
  TITLE = 'TITLE',
  HOURLY_RATE = 'HOURLY_RATE',
  OVERVIEW = 'OVERVIEW',
  VIDEO_OVERVIEW = 'VIDEO_OVERVIEW',
  AVATAR = 'AVATAR',
  HOURS_PER_WEEK = 'HOURS_PER_WEEK',
  VIEW_VIDEO_OVERVIEW = 'VIEW_VIDEO_OVERVIEW',
  PROFILE_VISIBILITY = 'PROFILE_VISIBILITY',
}
